### ISSUE TITLE
Installation fails on ubuntu 22.04

### ISSUE THREAD

**Issue by WildPenquin** [t-makaro/nb_pdf_template#28] opened 2022-05-18 19:40 UTC
Hi!

Installing the template according to instructions fails on the second command:

```
$ python3 -m nb_pdf_template.install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ville/.local/lib/python3.10/site-packages/nb_pdf_template/install.py", line 37, in <module>
    install()
  File "/home/ville/.local/lib/python3.10/site-packages/nb_pdf_template/install.py", line 21, in install
    raise OSError("Directory: %s not found." % dst)
OSError: Directory: /usr/lib/python3/dist-packages/nbconvert/templates/latex not found.

```

Obviously  /usr/lib/python3/dist-packages/nbconvert/templates/latex does not exist.

python3-nbconvert-6.4.0-1 installed system-wide.

**Comment by sutgeorge** [comment] 2023-10-17 19:45
I get the exact same error. I use PopOS 22.04.

**Comment by t-makaro** [comment] 2024-12-04 00:03
I'm closing this issue for the next version since it will use a very different template install mechanism (not really sure what it is) but nbconvert 6 was designed to make it less hacky. Feel free to reopen AFTER I put a new version in a few weeks if it's still an issue with nbconvert 7.

**Closed as completed by t-makaro** 2024-12-04 00:03 UTC
