### ISSUE TITLE
Error installing on Mac OS

### ISSUE THREAD

**Issue by wunken** [t-makaro/nb_pdf_template#26] opened 2021-02-11 06:12 UTC
**This looks like such a great template and I really want to use it! However I am running into an issue when I try to install it.** 
        
    $ python -m nb_pdf_template.install
    
      File "nb_pdf_template/__init__.py", line 1, in <module>
        from .jupyter_python import Jupyter_PythonStyle
      File "nb_pdf_template/jupyter_python.py", line 1, in <module>
        from pygments.style import Style
      File "pygments/style.py", line 171
        class Style(metaclass=StyleMeta):
                               ^
      SyntaxError: invalid syntax

**I manually installed as well, but am running into an error when trying to convert to PDF using the classic theme: (is this just a nbconvert issue?)** 

      $ jupyter nbconvert HW2_VBRF.ipynb --to pdf --template classic
      
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 608, in get_template_names
      raise ValueError('Unsupported mimetype %r for template %r, mimetypes supported are: \n\t%s' %\
      ValueError: Unsupported mimetype 'application/pdf' for template 'classic', mimetypes supported are: 
      text/html

**However nbconvert runs with classic theme if I convert to HTML instead of PDF. The styling does not look right in the HTML format of course**

      $ jupyter nbconvert HW2_VBRF.ipynb --to html --template classic
      
      [NbConvertApp] Converting notebook HW2_VBRF.ipynb to html
      [NbConvertApp] Writing 272518 bytes to HW2_VBRF.html

**Comment by wunken** [comment] 2021-02-11 06:34
I ended up creating a template based off of yours so that is working for me now ^_^ 

I still don't know what happened with this part though in case you wanted to check it out:

    $ python -m nb_pdf_template.install
    
      File "nb_pdf_template/__init__.py", line 1, in <module>
        from .jupyter_python import Jupyter_PythonStyle
      File "nb_pdf_template/jupyter_python.py", line 1, in <module>
        from pygments.style import Style
            File "pygments/style.py", line 171
              class Style(metaclass=StyleMeta):
                                     ^
            SyntaxError: invalid syntax

**Comment by bradleygrant** [comment] 2021-08-30 01:15
Wanted to update, I am having similar issues:

```
  File "/home/venv/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "/home/venv/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 526, in _template_paths
    template_names = self.get_template_names()
  File "/home/venv/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 616, in get_template_names
    raise ValueError('Unsupported mimetype %r for template %r, mimetypes supported are: \n\t%s' %\ 
  ValueError: Unsupported mimetype 'application/pdf' for template 'classic', mimetypes supported are:                             
          text/html  
```

**Comment by EdoWhite** [comment] 2022-01-13 17:26
I got the same error

**Comment by t-makaro** [comment] 2024-12-04 00:03
I'm closing this issue for the next version since it will use a very different template install mechanism (not really sure what it is) but nbconvert 6 was designed to make it less hacky. Feel free to reopen AFTER I put a new version in a few weeks if it's still an issue with nbconvert 7.

**Closed as completed by t-makaro** 2024-12-04 00:03 UTC
